root = "."
tmp_dir = "storage/temp"

[build]
  bin = "./storage/temp/main"
  cmd = "swag fmt && swag init -q --output ./app/swagger && go build -o ./storage/temp/main ."
  delay = 1000
  exclude_dir = [
    "frontend",
    "storage",
    "database",
    "app/swagger",
  ]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true
  rerun = true
  rerun_delay = 500

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
