
services:
  nginx:
    image: nginx:stable-alpine
    pull_policy: always
    restart: unless-stopped
    ports:
      - "3023:80"
    volumes:
      - ./:/app
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
  
  go:
    build:
      context: .
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    restart: unless-stopped
    environment:
      MONGODB_URL: mongodb://cuttuser:secret@mongo:27017/
    volumes:
      - ./:/app
      - go-cache:/go-cache
  
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: cuttuser
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: cutt
    volumes:
      - mongodb_data:/data/db
  
  redis:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    restart: unless-stopped
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
  
  frontend:
    image: node:latest
    restart: unless-stopped
    working_dir: /frontend
    ports:
      - "44447:44447"
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm install && npm run dev -- --host=0.0.0.0"
  
volumes:
  go-cache:
  mongodb_data:
  dragonflydata:
